name: Code Quality Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.2, 8.3]
        laravel-version: ['^12.0']

    name: PHP ${{ matrix.php-version }} - Laravel ${{ matrix.laravel-version }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pdo_mysql, bcmath
        coverage: xdebug

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-version }}-

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress --optimize-autoloader
        composer require "illuminate/framework:${{ matrix.laravel-version }}" --no-update
        composer update

    - name: Code Style Check (Laravel Pint)
      run: vendor/bin/pint --test

    - name: Static Analysis (PHPStan)
      run: vendor/bin/phpstan analyse --memory-limit=2G

    - name: Static Analysis (Psalm)
      run: vendor/bin/psalm --no-cache --shepherd --stats

    - name: Run Tests
      run: vendor/bin/phpunit --coverage-clover coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella